CREATE TABLE routines (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    type VARCHAR(100) NOT NULL,
    weight INTEGER NOT NULL,
    coefficient INTEGER NOT NULL,
    temporary BOOLEAN NOT NULL DEFAULT FALSE,
    disposable BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);